import { inter } from "./fonts";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Fashion Shop",
  description: "Generated by Fashion Shop",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable}`}
      suppressHydrationWarning={true}
    >
      <body>{children}</body>
    </html>
  );
}
